
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: myDataBase
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - type: volume
        source: my_db_data
        target: /data/db
volumes:
  my_db_data:
